title: Nick Brown | Software Developer
name: Nick Brown
email: nick@nick-brown.me
github_username: ncbrown1
linkedin_username: ncbrown1
spotify_userid: 121577201
twitter_username: ncbrown1

# Build settings
destination: docs/
exclude: ['Gemfile', 'Gemfile.lock', 'README.md']
gems:
  - jekyll-paginate
sass:
  sass_dir: _sass
markdown: kramdown
paginate: 5
paginate_path: "/blog/page:num/"
permalink: /blog/:year/:month/:day/:title

# plugin settings
related_project_keys: ["category", "technology"]
